### ISSUE TITLE
Hiding or locking the content

### ISSUE THREAD

**Issue by akramshahid314** [ananjaser1211/FloydQ_Reports#112]
We have already tripped Knox. I think so that private mode option must be added In next release.. may secure folder can be used with app lock instead of using Knox..  furthermore you can understand that what I suggest.. there must be a way to hide or lock personal contant

**Comment by ananjaser1211** [comment]
Both Secure folder and Private mode are no longer possible to be added.

Secure folder due to [this](https://github.com/ananjaser1211/FloydQ_Reports/issues/44#issuecomment-638171095)

And private mode has been dropped out of samsung firmware since Pie. and does not exist at all in Q. that feature is only on oreo.

You can use the Applock only to hide your apps. or just use a lock screen. those features are no longer possible, if you cant adapt without them revert to pie were secure folder works.
