### ISSUE TITLE
[BUG] Instagram camera

### ISSUE THREAD

**Issue by UntriexTv** [ananjaser1211/FloydQ_Reports#116]
I haven't got any problem with IG camera on V1 but now when I open camera in Instagram on v2 camera GUI is moved down (about 2.5cm)
Here is screenshot right from phone
![Screenshot_20200621-205224_Instagram](https://user-images.githubusercontent.com/48880229/85232709-56a76780-b401-11ea-8f61-e3c353e83fc3.jpg)

**Comment by UntriexTv** [comment]
edit *0.5 cm

**Comment by UntriexTv** [comment]
I had an aspect ratio problem too on v1 with vlc media player. I haven't tested it jet on v2. But when I was watching Livestream from my satellite video was narrowed (? sorry I don't know English well). Changing aspect ratio in vlc doesn't change anything (Friend on iPhone 10 haven't got any problem with that stream in VLC). I will try it tomorrow (within 21 hours) on vlc and other apps that work with video and send screenshots (on Floyd v2).

**Comment by SkyrilHD** [comment]
Hi,

I don't have any issues with Instagram Camera. Do you have navbar enabled in aroma?

**Comment by UntriexTv** [comment]
No, I remember that i disabled it.

**Comment by ananjaser1211** [comment]
some Apps that read aspect ratio from the framework will think there is a navbar, because the bool for that is now framework.jar compared to Pie

we cant edit that without breaking half the ROM. so it will stay like that. 

P.S : picking navibar and disabling it from the settings are not the same. because it will add a gap once it is there regardless, but again, detection is app based
