### ISSUE TITLE
[BUG]Google Detects custom OS

### ISSUE THREAD

**Issue by Divakar37** [ananjaser1211/FloydQ_Reports#148]
Previously on V2.0 I could use my University provided Gmail on my S7E but on V3.0 Google does not allow to install a app which is required to create a work profile.
![bug](https://user-images.githubusercontent.com/64517946/88075866-16bad800-cb99-11ea-89b5-9d35fdbae4fc.jpeg)

**Comment by ananjaser1211** [comment]
This seems to be Knox related, even tho the knox packages from V2 are now installed by default (instead of removable via aroma) so not really sure what went wrong, I have zipped the knox apps from V2 here, flash it and let me know if its gone. if not i think you need to take a non filtered log to see if this is knox or some new security measure in Oneui 2.1 / gmail

[Knox.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/4956221/Knox.zip)

**Comment by Divakar37** [comment]
> This seems to be Knox related, even tho the knox packages from V2 are now installed by default (instead of removable via aroma) so not really sure what went wrong, I have zipped the knox apps from V2 here, flash it and let me know if its gone. if not i think you need to take a non filtered log to see if this is knox or some new security measure in Oneui 2.1 / gmail
> 
> [Knox.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/4956221/Knox.zip)

I did flash the zip, didn't work

**Comment by ananjaser1211** [comment]
> > This seems to be Knox related, even tho the knox packages from V2 are now installed by default (instead of removable via aroma) so not really sure what went wrong, I have zipped the knox apps from V2 here, flash it and let me know if its gone. if not i think you need to take a non filtered log to see if this is knox or some new security measure in Oneui 2.1 / gmail
> > [Knox.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/4956221/Knox.zip)
> 
> I did flash the zip, didn't work

So it is not lack of Knox, do you have magisk installed ? i was reading about this issue here https://github.com/topjohnwu/Magisk/issues/2181 but im not sure if its fully relevant.

beyond that, there was nothing more changed in V3 that would affect such security from my end, unless samsung has included something more in oneui 2.1 but idk.

i am still able to add my uni email through gmail > exchange. but i dont have a edu google account to test. i also dont have magisk installed right now

![image](https://user-images.githubusercontent.com/25624482/88186224-fac14000-cc45-11ea-8fdd-4980b479b8fd.png)

**Comment by Divakar37** [comment]
> > > This seems to be Knox related, even tho the knox packages from V2 are now installed by default (instead of removable via aroma) so not really sure what went wrong, I have zipped the knox apps from V2 here, flash it and let me know if its gone. if not i think you need to take a non filtered log to see if this is knox or some new security measure in Oneui 2.1 / gmail
> > > [Knox.zip](https://github.com/ananjaser1211/FloydQ_Reports/files/4956221/Knox.zip)
> > 
> > 
> > I did flash the zip, didn't work
> 
> So it is not lack of Knox, do you have magisk installed ? i was reading about this issue here [topjohnwu/Magisk#2181](https://github.com/topjohnwu/Magisk/issues/2181) but im not sure if its fully relevant.
> 
> beyond that, there was nothing more changed in V3 that would affect such security from my end, unless samsung has included something more in oneui 2.1 but idk.
> 
> i am still able to add my uni email through gmail > exchange. but i dont have a edu google account to test. i also dont have magisk installed right now
> 
> ![image](https://user-images.githubusercontent.com/25624482/88186224-fac14000-cc45-11ea-8fdd-4980b479b8fd.png)

No, I don't have magisk installed and it may have happened because of some security changes in Oneui2.1 idk

**Comment by ananjaser1211** [comment]
This issue should be fixed in the next release , WorkProfile (What also runs secure folder) has been spoofed and fixed

**Comment by SmartBoy84** [comment]
eta wen?
