### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xraive** [ananjaser1211/FloydQ_Reports#151]
I'm having issues using the AirAudio app.  I have Samsung Radiant 360 R1 Multiroom Speakers and Samsung Soundbar MS650.  When trying to stream audio to the speakers the app crashes.  This app works fine on some Roms and stock. But I have had problems on V1,V2, and V3 of this ROM.

1. Open the Airaudio app and wait until it scans your network for audio receiver devices.
2. Click on the Samsung Speaker/Soundbar if you have one and it will crash.
3. The app will crash and exit.

Normally if you select the speaker or soundbar it should stream the audio from the phone to the speakers.

Screenshotts

![Screenshot_20200721-215151_One UI Home](https://user-images.githubusercontent.com/17913801/88125159-add55f00-cb9c-11ea-874d-0c18b9486431.jpg)

![Screenshot_20200721-215101_One UI Home](https://user-images.githubusercontent.com/17913801/88125184-b62d9a00-cb9c-11ea-82ea-4259975258ab.jpg)

![Screenshot_20200721-214911_One UI Home](https://user-images.githubusercontent.com/17913801/88125204-be85d500-cb9c-11ea-8f0b-216e153c9324.jpg)

Smartphones
 - Device: Galaxy S7/S7Edge
 - Model: G930W8/G935W8

Logs
[AirAudioLog.txt](https://github.com/ananjaser1211/FloydQ_Reports/files/4957458/AirAudioLog.txt)

Just wanted to also say thank you for all your efforts.  This ROM id amazing and breathed new life onto this phone.  

It's my first time reporting an issue so I hope I provided all the info you're looking for.  If there is any additional information I can provide please let me know.

**Comment by ananjaser1211** [comment]
Based on the Crash, this issue is due to the app not supporting Oneui 2 / Q . I cant fix this from my side. your issue report is great and had all the information, but its not something i am able to fix.

the app seems to be calling old methods that were deprecated or removed. if its possible you have to reach out to the app developer for an update. meaning you will have to use older ROMs until they update it if ever.

07-21 22:04:15.647 E/AndroidRuntime(30053): FATAL EXCEPTION: Thread-15
07-21 22:04:15.647 E/AndroidRuntime(30053): Process: eu.airaudio, PID: 30053
07-21 22:04:15.647 E/AndroidRuntime(30053): java.lang.**NoClassDefFoundError**: Failed resolution of: Lorg/apache/http/RequestLine;
07-21 22:04:15.647 E/AndroidRuntime(30053): 	at c.f.a.c.i.a(AsyncHttpClient.java:37)

**Comment by xraive** [comment]
Thanks for your quick response.  I'll get in touch with the developer.  I'll stick with your ROM and hopefully the app will be upgraded.  Thanks for the great work.
