### ISSUE TITLE
[BUG] CIDManager pop-up

### ISSUE THREAD

**Issue by limvaldez** [ananjaser1211/FloydQ_Reports#154]
**Describe the bug**
"Restart phone" button is keep on popping up. But their is still an option. If you want to use this rom, remove the simcard. Because if you insert your simcard, this rom is suggesting you to restart your phone over and over again.

**To Reproduce**
1. When you turn off your phone and turn in on again, the system ui will ask you to restart your phone(This bug must be mark as an urgent)
2. Do not press the cidManager in notification center. If you select that accidentally, your phone will keep you on asking to restart your phone.

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
![Screenshot_20200723-142719_Settings](https://user-images.githubusercontent.com/64057182/88259598-39620380-ccf5-11ea-9420-432fa9bb1761.jpg)
![Screenshot_20200723-143235_One UI Home](https://user-images.githubusercontent.com/64057182/88259610-3ebf4e00-ccf5-11ea-82bd-798caf51229e.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930FD]

PS: I'm from philippines

**Comment by ananjaser1211** [comment]
There is a workaround written in the F.A.Q page for this.

But I'll keep this up until the OXM package zip is released. It won't change this behavior

**Comment by limvaldez** [comment]
> There is a workaround written in the F.A.Q page for this.
> 
> But I'll keep this up until the OXM package zip is released. It won't change this behavior

Sorry, i did not read that section carefully. But thanks for responding.

**Comment by ananjaser1211** [comment]
So, While i tried to solve this BUG "Normally" it seems to not be feasible, it is more likely related to having installed a pie ROM with omc before or not, or something that generated the proper country code for each device + the OMC package having the needed country.

Due to our custom OMC package, a mismatch seems to happen somewhere. I might try and Hide the pop up or mute it or something but while keeping the app in place (removing CIDManager before it runs once will prevent the country network info and such from loading properly)

**So for now, To hide CIDmanager popup, Delete the APK from /system/system/priv-app/CIDManager/CIDmanager.apk**

until a more proper solution is found

**Comment by SypeR54** [comment]
For our tester reported **CIDManager** fixed in new test build on both variants (Single SIm/Dual SIM). I marked it as "Fixed in next release". Thanks for reporting @limvaldez .

**Comment by SypeR54** [comment]
**Update:** CIDManager pop-up issue completely fixed by patching CIDManager apk. Thanks for patch for the @ananjaser1211 . Now its completely fixed.
