### ISSUE TITLE
[BUG] Heart rate sensor doesn't work in camera

### ISSUE THREAD

**Issue by ayam12** [ananjaser1211/FloydQ_Reports#160]
Heart rate sensor in selfie mode doesn't work .

**Comment by ananjaser1211** [comment]
This wont be fixed further as samsung camera in Q handles HR shutter differently. there is some region lock going on were it only works in some CSCs. i have not been able to figure it out yet. it will work for some, and wont work for the rest.

if there is any proper fix ill update this post

**Comment by SypeR54** [comment]
In Samsung Camera Q, HR shutter based on hard-coded mobile device support. For now, @ananjaser1211 make some progress on the fix. But still we need the figure out other security enhancements and patch them. Because of that, i'm not removing the "wontfix" label but due to some progress, we believe we can manage to fix it one day, so i'm adding "bug" label too.

**Comment by ananjaser1211** [comment]
HeartRate sensor has been patched in the camera and now works on selfies
