### ISSUE TITLE
[BUG] Applications on device assistance reset

### ISSUE THREAD

**Issue by souzajerry** [ananjaser1211/FloydQ_Reports#165]
good night, here in Brazil hihi, device assistance does not recognize installed applications, follow print
![Screenshot_20200810-022814_Device care](https://user-images.githubusercontent.com/66040178/89754327-d375ca00-dab1-11ea-8d5a-c7d5cac4d844.png)

Galaxy S7 Edge
SM-G935F

**Comment by ananjaser1211** [comment]
Ill look into it soon

**Comment by souzajerry** [comment]
Thanks

**Comment by souzajerry** [comment]
good night king @ananjaser1211, just to let registered that this error occurs in the assistance of the device and in the settings, follows prints
![Screenshot_20200811-231728_Link2SD](https://user-images.githubusercontent.com/66040178/89968010-33db4780-dc29-11ea-9a4e-aefce491b64d.png)
![Screenshot_20200811-231743_Settings](https://user-images.githubusercontent.com/66040178/89968014-350c7480-dc29-11ea-905c-0d94ba714f54.png)

**Comment by SypeR54** [comment]
@souzajerry On newer Android versions, Link2SD has some linking issues i guess

**Comment by souzajerry** [comment]
but the issue is the error in the device settings, I used the link2sd to demonstrate the actual size

**Comment by SypeR54** [comment]
@souzajerry

**Comment by SypeR54** [comment]
> but the issue is the error in the device settings, I used the link2sd to demonstrate the actual size

it dedected on me without issues

![image](https://user-images.githubusercontent.com/12627005/89968565-c5b07800-dc5c-11ea-87ad-b364540454a3.png)

**Comment by souzajerry** [comment]
when you restart, change the size for me

**Comment by SypeR54** [comment]
@souzajerry Look, on me there is no issue. Before and after, values are same. I suggest you to make clean flash and dont install any mod (magisk modules, link2sd etc). Then check again.

Before reboot Device Care + Advanced usage view
![image](https://user-images.githubusercontent.com/12627005/89969315-bfbb9680-dc5e-11ea-8d73-a41399e9be16.png)
![image](https://user-images.githubusercontent.com/12627005/89969330-c4804a80-dc5e-11ea-8516-0b525509e557.png)

----
After reboot Device Care + Advanced usage view
![image](https://user-images.githubusercontent.com/12627005/89969436-0f01c700-dc5f-11ea-9f0c-99910103a98c.png)
![image](https://user-images.githubusercontent.com/12627005/89969441-11642100-dc5f-11ea-87db-5b2049644845.png)

**Comment by souzajerry** [comment]
when I installed it I did a clean flash but thanks, but I still think it may be a bug, I can't perform tests due to some bank apps, but thanks

**Comment by SypeR54** [comment]
@souzajerry Your welcome. Still i'll try to replicate your issue but i think there is some modded/broken file. Maybe thats the reason why it can't calculate. Also how much bloatware you selected when installing the rom?

**Comment by souzajerry** [comment]
I can't remember but I selected a few

**Comment by SypeR54** [comment]
Alright, i found why its shows 0 app in apps list. In updated "Device Care" it checks unused apps, not used apps. With this change app says "There is 0mb free space from removed unused apps.". If you install new app from Google Play and never run it, it directly shows under this section (check screenshot 1 and 2). If you run them for the first time, its removed from there because app now listed as "used" (check screenshot 3 and 4).

@ananjaser1211 You can tag it as  "invalid" BUG.

**Screenshot 1 and 2:**
![image](https://user-images.githubusercontent.com/12627005/90146872-41f4a980-dd8a-11ea-8e17-9ab10d40b3fc.png)
![image](https://user-images.githubusercontent.com/12627005/90146889-46b95d80-dd8a-11ea-8fd1-595be06ccb32.png)


**Screenshot 3 and 4:**
![image](https://user-images.githubusercontent.com/12627005/90146981-5f297800-dd8a-11ea-941c-e42da0c8cf1a.png)
![image](https://user-images.githubusercontent.com/12627005/90147009-651f5900-dd8a-11ea-9b86-712b8b795f02.png)

**Comment by ananjaser1211** [comment]
Thank you for the assistance @SypeR54
