### ISSUE TITLE
 floyd q rom also for s8

### ISSUE THREAD

**Issue by MaSKFG** [ananjaser1211/FloydQ_Reports#174]
will a version for s8 arrive soon? Because in my opinion it is important that it also arrives on these devices.

**Comment by SkyrilHD** [comment]
No, since this ROM only supports 8890 meaning S7/S7E/N7/NFE... So this ROM will not be supported for the S8 since it uses a different SoC (8895)

**Comment by MaSKFG** [comment]
> No, since this ROM only supports 8890 meaning S7/S7E/N7/NFE... So this ROM will not be supported for the S8 since it uses a different SoC (8895)


won't there be a version for Exynos 8895?

**Comment by SkyrilHD** [comment]
No

**Comment by MaSKFG** [comment]
> No

I'm sad now ;(

**Comment by SypeR54** [comment]
No, Floyd Q for Exynos 8895 never released. There is 3 reason.
1. Anan doesn't have any Exynos 8895 based device.
2. Corsicanu already have Exynos 8895 based devices and maintaining this family.
3. Corsicanu already ported and booted Samsung Q rom on Exynos 8895. However, due to lack of HWC driver issues it's not ready for daily usage. Because of that, it will never released to the public.

I hope you understand the sitution. I suggest you to upgrade a newer devices (such as S9 or Note 9 atleast) or enjoy with Corsicanu's Hades Pie rom.

**Comment by MaSKFG** [comment]
> No, Floyd Q for Exynos 8895 never released. There is 3 reason.
> 
> 1. Anan doesn't have any Exynos 8895 based device.
> 2. Corsicanu already have Exynos 8895 based devices and maintaining this family.
> 3. Corsicanu already ported and booted Samsung Q rom on Exynos 8895. However, due to lack of HWC driver issues it's not ready for daily usage. Because of that, it will never released to the public.
> 
> I hope you understand the sitution. I suggest you to upgrade a newer devices (such as S9 or Note 9 atleast) or enjoy with Corsicanu's Hades Pie rom.

thanks, but i dont think to install the hades pie rom ... i would like to install the one ui 2.1 and andorid 10

**Comment by ananjaser1211** [comment]
> will a version for s8 arrive soon? Because in my opinion it is important that it also arrives on these devices.

Sure it is important, but i dont make roms out of thin Air, and i dont have any 8895 device to do so.

wait until corsicanu figures out how to make it work properly, if ever.
