### ISSUE TITLE
[BUG] S7 bricked. bit hard to get logs on this one.

### ISSUE THREAD

**Issue by bodhirobinson** [ananjaser1211/FloydQ_Reports#179]
**Describe the bug**
I flashed Floyd Q 4.0 early this morning, all was well, clean flashed. During the day I had some random crashes where I had to force restart to use the phone again. Just before, I got crashed again, but this time it permanently bricked my S7. It no longer responds to charging, I can't get it to boot or show any signs of life. rip.

**To Reproduce**
i literally was just using my phone, taking pictures, answering messages
**Expected behavior**
the phone to not crash lol

**Screenshots**
uhh they're a bit hard to get right now considering my phone is hard bricked

**Smartphone (please complete the following information):**
galaxy s7
g930f

**Additional context**

yet again i can't get logs

**Comment by bodhirobinson** [comment]
it's been 40 minutes since my phone got hard bricked and it's showing no signs of life. won't charge, none of the leds work, can't boot into download/recovery/any mode. If anyone knows how to fix this please shoot me an email at bodhirobinson@outlook.com or send me a dm on my instagram @bodhirobinson9 i really need to use this phone for stuff. uhh yeah that's about it

**Comment by bodhirobinson** [comment]
actually i meant floyd 4.0 above^^

**Comment by SypeR54** [comment]
@bodhirobinson These issues happens when NAND based internal storages (eMMC, UFS etc) corrupted. This corruptions happened on logical gates and cant be fixed until they replaced with a new one.

You need the send your phone to some professipnal repair shop who have experience on NAND replacement. But this is a expensive repair, so i suggest you to replacing whole motherboard instead NAND chip. Its cost less and work guaranteed. Also easy to replace.

PS: I'm closing the issue report because it's not the rom releated issue. It's your phone fault.

**Comment by ananjaser1211** [comment]
This might sound stupid. But keep the phone plugged in to the wall. It won't show anything on screen but leave it. For like hours.

I had this exact same thing happen on my J5 2017 last year. Zero signs of life. Kept it plugged in and it just worked.

It could be a UFS failure like Yasin mentioned. Hopefully it's not.

I've been reading about S7s dying out if the blue for the past few months now on reddit and on telegram. Not sure why really but some update released between Jan/Mar is breaking some phones. Regardless wether it's stock ROM. Ported rom etc 

For now. Try to keep it plugged in

**Comment by ananjaser1211** [comment]
@bodhirobinson Perfect !
