### ISSUE TITLE
[BUG] Photos from Samsung Cloud / OneDrive not appearing.

### ISSUE THREAD

**Issue by Selembung** [ananjaser1211/FloydQ_Reports#187]
![Screenshot_20200906-224152_Gallery](https://user-images.githubusercontent.com/24208515/92329538-3303cd00-f092-11ea-8ddb-8b4327b13a4c.jpg)

**Comment by ananjaser1211** [comment]
Bug exists since V2, even tho there is no change done to any of samsungs sync apps. unclear why this happens

**Comment by SypeR54** [comment]
Can you try to collect Verbose (log_all.bat) log before opening the Gallery and add here? Thanks.

**Comment by Selembung** [comment]
> Can you try to collect Verbose (log_all.bat) log before opening the Gallery and add here? Thanks.

How to do it?

**Comment by SkyrilHD** [comment]
Download this repo on your computer and turn on ADB Debugging in developer options on your phone. Then connect the phone to your computer and run Log_e.bat. After your command prompt pops up, open gallery and play around a bit. Then close the command prompted and post the log-all.log here.

**Comment by rsspeed** [comment]
I had already asked about it on xda.

 https://forum.xda-developers.com/showpost.php?p=83400747&postcount=1755

will it be fixed?

**Comment by SkyrilHD** [comment]
If someone sends a log about this issue, the devs will look into it

**Comment by rsspeed** [comment]
would if I knew how

![2020-09-09 15_29_31-Window](https://user-images.githubusercontent.com/71007033/92604953-6c665380-f2b1-11ea-865d-24bdf8eb4883.jpg)

**Comment by SypeR54** [comment]
@rsspeed Dont use "run" prefix. Just log_all.bat or just double click the "log_all.bat" file. It will done rest of the process.

**Comment by rsspeed** [comment]
without "run" nothing happens in the CMD window

i don`t know where i must a double click on the "log_all.bat" file, i found them not

**Comment by SkyrilHD** [comment]
The easiest way would be to download this repo and run it that way.

1. Download this repo 
2. After you extracted the zip, open the folder
3. Go to your current OS' folder
4. Double click on Log_all.bat
5. Open the gallery on your phone and play around with it 
6. Close the CMD window and send it here

**Comment by rsspeed** [comment]
Sorry but i don`t finde the repo zip :-(

**Comment by SkyrilHD** [comment]
Here is the link:

https://github.com/ananjaser1211/FloydQ_Reports

Go to the green button which says Code, then click on 'Download ZIP'

**Comment by Selembung** [comment]
Here the log-all.log
[log_All.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5196279/log_All.log)

**Comment by rsspeed** [comment]
[log_All.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5196523/log_All.log)
and here ist my log-all.log
thx @SkyrilHD

**Comment by SypeR54** [comment]
@Selembung Thank you for logs. I'll check them when i'm free.

**Comment by rsspeed** [comment]
Is there any solution to fix this problem?

**Comment by ananjaser1211** [comment]
would have been marked as patched/fixed if that is the case.

there is no fix yet, and it seems that post april Q, something has changed and broke thumbnail perms

`09-09 18:14:07.745 25311  1730 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/sec/cloud/0/thumbnail/15765011370000ba9551e2ae69d0b.jpg: open failed: EACCES (Permission denied)`


the same issue happens on custom S9+ rom on that device and on my other Q port for the note8 (so without debloating and anything) 

it will upload photos you take to the cloud, but it wont retrieve old ones / use the thumbnail from samsung cloud

we can see that it retrieves the thumbnail just fine

`09-09 18:14:07.743 25311 25311 I Gallery : [1359:ImageViewerFragmen/8] onSlideIn MediaItem{i,0,2147505738,-1798584492,Cloud (320,320,0,0:1576497537000,1576526072,image/jpeg:-1,0:true:null:2147505738//data/sec/cloud/0/thumbnail/15765011370000ba9551e2ae69d0b.jpg) ,67ezXL2Til49hdOKYhWHil48v4pePc+KXj2XimIVj4piFL+KYhWNs4piFb3Xil49kL+KYhTDil48v4pePdOKYhWjimIV14piFbeKYhWJu4piFYWnil49sLzHimIU14piFN+KYhTbimIU14piFMOKYhTHimIUx4pePM+KXjzfil48wMDDimIUw4piFYuKYhWE54piFNeKYhTXil48x4piFZeKYhTJh4piFZTY54piFZDBiLuKXj2ril49w4pePZw==riBKhqg}`

but it fails to decode it due to a permission issue somewhere

`09-09 18:14:07.745 25311  1730 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/sec/cloud/0/thumbnail/15765011370000ba9551e2ae69d0b.jpg: open failed: EACCES (Permission denied)`

so something in `/data/sec/cloud/` got messed up somewhere. it is a place to start, if anything happens ill update this issue

**Comment by ananjaser1211** [comment]
This bug wont be fixed, ill be marking it as technical limitation, as the same bug exists on rooted S9+ with custom roms. 

not sure if samsung tied cloud to knox or whatever they have done in Q. but im tired of chasing empty leads. 

if at any time in the future something shows up about this, we can revist
