### ISSUE TITLE
[BUG] The screen remains on

### ISSUE THREAD

**Issue by Selembung** [ananjaser1211/FloydQ_Reports#192]
The screen keeps on turning on even though I have set the screen timeout 30s

**Comment by Selembung** [comment]
The screen keeps on turning on even though I have set the screen timeout 30s

**Comment by ananjaser1211** [comment]
Refer to #183 

This is caused by some userapp you have installed. the issue does not exist here or on fresh installations of the ROM

**Comment by Selembung** [comment]
But why does this happen when the smartphone is being charged.

**Comment by ananjaser1211** [comment]
> But why does this happen when the smartphone is being charged? When not in charge, the screen timeout goes well.

Must be an app that just keeps the screen on, you have to check, i just plugged in the phone and it times out just fine.

**Comment by Selembung** [comment]
I've been trying like this
1. The screen on the homescreen and the smartphone is being charged, the result is the screen remains on, even though I set the screen timeout to 30 seconds.
2. The screen on the homescreen and the smartphone is not in a charging state, and the screen turns off like normal nothing strange

**Comment by SypeR54** [comment]
Can you check please "Settings > Screen > Screensaver" menu? Do you have any selected screensaver?

**Comment by Selembung** [comment]
None selected

**Comment by ananjaser1211** [comment]
Any updates on this, clean flashed the ROM, no issue. 

restored my backup + installed my daily apps (twitter reddit debugging apps filemanagers and magisk etc) the screen lock is still working fine.

please run logcat when you leave the screen on and attach it here (log_v in logging kit and log_e) maybe it will show something

so far this remains some APP issue, not a ROM issue since it does not happen with a fresh install / generic user apps installed

**Comment by Selembung** [comment]
I can't find log_v in the Floyd Report folder, so I'm just sending log_e. But can you tell me where the log_v is?
[log_e.log](https://github.com/ananjaser1211/FloydQ_Reports/files/5254424/log_e.log)

**Comment by Selembung** [comment]
I found this a lot HWComposer: onVsync failed for HWC display 0: Invalid HWC display, is these the problem?

**Comment by ananjaser1211** [comment]
your phone is having a big number of invalid HWC display. these warnings occurs when the camera is operating. 
i think your phone is not locking due to smart Stay

i can confirm smart stay is working fine (my screen wont lock if i set it to 15 seconds + look at the display with smart stay on)

smart stay can be  found in advanced features > motion and gestures > smart stay

**Comment by Selembung** [comment]
But this smartphone screen stays on when it's on the charger, when the smartphone isn't on the charger, the smartphone screen turns off as it should

**Comment by SkyrilHD** [comment]
Hi, can you check if this is enabled in Developer options?

![Screenshot_20200921-223803_Settings](https://user-images.githubusercontent.com/28839925/93818874-38990f80-fc5b-11ea-80e9-18baff863e88.jpg)

**Comment by Selembung** [comment]
Hahahaha I think I know the problem, thanks problem solved😄

**Comment by ananjaser1211** [comment]
Glad its solved. thanks @SkyrilHD
