### ISSUE TITLE
[Feature] Dolby ATMOS Gaming profile (Fix spatial / surround issue in games eg. PUBG)

### ISSUE THREAD

**Issue by ArifAGA98** [ananjaser1211/FloydQ_Reports#195]
The sound of the game does not work correctly when Dolby Atmos is turned on.

**Comment by SkyrilHD** [comment]
"does not work correctly"....

Can you please explain what you mean, since the testers found no issues.. if you could be precise then we could look further into the issue

**Comment by ArifAGA98** [comment]
This problem only occurs when pubg is turned on. There are fluctuations in
the interface music and effects of the game.

19 Eyl 2020 Cmt 19:04 tarihinde SkyrilHD <notifications@github.com> şunu
yazdı:

**Comment by ananjaser1211** [comment]
the sound difference when dolby is enabled in PUBG is just louder as far as i can see. i will keep this open until i have more time to test as i only tested a 5 minute game, but again i did not notice issues yet on my end

**Comment by ArifAGA98** [comment]
Yes, the sound of the game is louder, but there are problems that can be
understood with the headphones in the effects of the game.  For example,
footprints and conflict sounds are not coming from the right direction.

20 Eyl 2020 Paz 02:06 tarihinde AnanJaser <notifications@github.com> şunu
yazdı:

**Comment by ananjaser1211** [comment]
Ah headphones use, this might be due to how dolby operates, it can merge L/R channels and creates its own spatial system. 
in note 9 firmwares there is dolby Gaming mode which adds the dolby improvements, without affecting the gaming sound direction etc

but i was unable to bring this feature to the S9 base yet. this could be why its not working well. i remember playing pubg on my S9+ Device with headphones and yeah i can remember the voices were not from the right directions with dolby enabled

i will mark this as feature request for dolby gaming mode

**Comment by SypeR54** [comment]
Due to new fixes included in V5, i'm closing the bugs and marked as "Addressed". Thanks for your report, effort and help.
