### ISSUE TITLE
[Feature] DUAL IMSI / 4G/4G / Dynamically switch SIM networks in dual sim mode

### ISSUE THREAD

**Issue by Itzsrohit** [ananjaser1211/FloydQ_Reports#197]
**Describe the feature**
In dual sim model only one sim can be 4g and other in 2g/3g. Here the network provider which i use one of them offer 4g only and another one is 2/3/4g  . So the thing is whenever i wnat to use data from another sim the 4g only goes to 2g/3g mode. So no network in that sim then.
Is there any way/mod to use 3g data in another sim and keep that 4g only sim for calling/message .
It'll be really useful for users like in INDIA where some network provider offers 4g only service and we can't utilize  data from second sim.

**Comment by ananjaser1211** [comment]
This bug is because our device does not support samsungs DUAL IMSI . i.e Dual LTE . 

In pie, we could disable functionality of dual LTE (so it behaves 1 sim 4g and automatically drop the other sims to 3g when needed)
This has since been deprecated in Q and cant be brought back, so for dual sim users with both 4G, they have to either use both at 3G, or manually switch 4G on/off on either sims.
