### ISSUE TITLE
[Feature] Encryption support

### ISSUE THREAD

**Issue by kathir28** [ananjaser1211/FloydQ_Reports#198]
Encryption has been disabled on FloydQ V4, can it be supported in the future?

**Comment by ananjaser1211** [comment]
No sorry, i am not interested in encryption on custom ROMs. it takes way too much effort and enabling it might causes issues with other users and lock their data.

**Comment by gitoss** [comment]
Of course as the dev you're free to prioritize at your leasure (did it work until Floyd v3)? 

But imho this is a major drawback vs. aosp, and the lack of encryption support isn't mentioned in the release notes. Some data can be hidden in EncFS or the like, but with TWRP a lot of sensitive app data is for the taking with no effort at all after losing the phone.

I hope, you can reconsider :-) Thanks.

**Comment by kathir28** [comment]
> Of course as the dev you're free to prioritize at your leasure (did it work until Floyd v3)?
> 
> But imho this is a major drawback vs. aosp, and the lack of encryption support isn't mentioned in the release notes. Some data can be hidden in EncFS or the like, but with TWRP a lot of sensitive app data is for the taking with no effort at all after losing the phone.
> 
> I hope, you can reconsider :-) and enable it at least on a "unsupported take it or leave it basis"? Thanks.

+1, i left floyd due to the lack of encryption, but the rest of the rom is very good! :D

**Comment by ananjaser1211** [comment]
This issue was supposed to stay open but as a "won't fix , bug" for visibility 

Right now I can't figure out why encryption won't work.

Keymaster can't edit / use our fstab file in / but I can't seem to figure out why. Initially I suspected it is due to old mcregistry / tee combo but the same issue shows up in oneui Q port on the 8895. Still outdated keymaster but not as much as the S7

I'll try to take another look when I have the chance. As any attempts to log or try encryption breaks my data.

And no it never worked in any release as far as I remember.

The only workaround as you mentioned is encFS / secure folder.

**Comment by ananjaser1211** [comment]
Encryption will available in V8.0

**Comment by ananjaser1211** [comment]
Closed as V8 is now out with a fix for this bug https://xdaforums.com/t/rom-10-0-oneui-2-5-g930x-g935x-n930x-n935x-floydq-v8-0.4085667/post-89144172
