### ISSUE TITLE
[Feature] New camera modes (i.e Motion photos, Single Take camera etc)

### ISSUE THREAD

**Issue by syashbrl37** [ananjaser1211/FloydQ_Reports#202]
i couldn’t get the feature request section so, i posted here. Please Add motion photos and single take camera mode, they will be really sick

**Comment by SypeR54** [comment]
**Describe the feature**
Please add more camera modes in camera options like motion photos (live photos) and single take camere modes.

> **What is Motion Photo?**
> Motion Photo puts a little context into the making of the shot by letting you capture a few seconds of action leading up to when the shutter button is released. It even allows you to pinpoint which moment you want to preserve as the still frame. Also, when it comes to sharing photos with friends and family, you have the option to share the Motion Photo as a video file.
> 
> Motion Photo is available on Galaxy S20, S20+, S20 Ultra, Z Flip, Note10, Note10+, S10e, S10, S10+, Fold, Note9, S9, S9+, Note8, S8, S8+, S7, and S7 edge.
> 
> [Discover more about Galaxy for yourself.](https://www.samsung.com/global/galaxy/what-is/motion-photo/)

> **What is Single Take on Galaxy?**
> Introduced on the Galaxy S20, S20+, and S20 Ultra, Single Take is a whole new way to capture the moment. Or, should we say, whole new ways! When you use Single Take, you tap the shutter once and move around a bit to capture the moment from different angles.
> 
> You can capture up to 10 seconds, and you’ll get a variety of styles, angles, and formats created automatically. All you have to do is be in the moment to get different kinds of shareable options in your Gallery.
> 
> [Discover more about Galaxy.](https://www.samsung.com/global/galaxy/what-is/single-take/)
> 
> *Single Take is available on previous Galaxy series when upgraded to Android 10.
> *The format and amount of Single Take results may differ based on original capture.

**Possible Visualization**

- Single Take feature:
https://images.samsung.com/is/content/samsung/p5/uk/support/mobile-devices/galaxy-s20/galaxy-s20-single-take.gif

- Motion photo feature:
![image](https://user-images.githubusercontent.com/12627005/94992615-f5f90080-0593-11eb-8625-73e751d6087c.png)


**Expected behavior**
As shown in visualizations, it must be capture 10 photos and 4 videos at the same time or it must be capture 1 photo with embedded 3 secs gif video.

**Smartphone (please complete this feature following information part if you want device spesific):**
 - Device: S7, S7e and N7, N7FE
 - Model: G930x, G935x and N930x, N935x

**Origin of Feature**
- For Motion Photos, S7 from Marshmallow+ firmwares.
- For Single take capture, any flagship device OneUI 2.0+ firmwares.

**Comment by SypeR54** [comment]
I'm not sure, motion photos will be work on this patched camera blobs. However, for single take capture our device probably cant handle it due to lots of required power. Because single take feature, captures many photos, videos from different camera sensors (which is we have only single camera) at the same time. So implementing it maybe hard or even worse, unneccessary.

Anyway, we will try to improve and add these modes in the camera app. I hope we can manage it and can share them to the public in future releases of rom.

Thanks for your feature request.

**Comment by ananjaser1211** [comment]
Both features cant be implemented

Motion photo implementation in Q breaks our camera server (as its only designed and intended for CoreV2 devices, which we are not)

Samsung also removed motion photo support from any of their legacy camera devices (CoreV1) such as A750. meaning we dont have a source to port this feature from
i will only add the motion photo viewer back since some users want to playback existing media

Single take is also only implemented in CoreV2 devices. cant be ported either
