### ISSUE TITLE
[BUG] possible malware in all android 10 devices

### ISSUE THREAD

**Issue by samuraikidXDA** [ananjaser1211/FloydQ_Reports#205]
com.samsung.android.server.wifi.mobilewips.client     
# People of reddit saying it's a new type of malware build into new devices that does dns queries 

please remove it 
Stay safe & 
Thanks for the good job,
pointing to privacy

**Comment by ananjaser1211** [comment]
This is a native samsung app. provided from samsung themselves, i very much doubt it has any malware tendencies otherwise we would be hearing about a lawsuit. 

many samsung apps (especially YUVA) have URLs and requests for servers all over the world, i wont be surprised if this is a normal query. recently reddit also found another "malware" which turned out to be nothing malicious, 

feel free to remove the APK yourself, i wont be removing it as i dont want to bother debugging what happens without it

**Comment by samuraikidXDA** [comment]
i did already and its all good
https://www.reddit.com/r/onions/comments/esaes7/weird_packet_capture_from_my_wifes_phone/

**Comment by ananjaser1211** [comment]
I saw the thread, all speculation, no actual evidence of malware activity. if having broken DNS queries was a point of concern, a big chunk of samsung apps will be "malware"

**Comment by samuraikidXDA** [comment]
Ok thanks for replying

**Comment by samuraikidXDA** [comment]
You were right it breaks wifi network search but if you are already connected to the network it will connect just cant acess network list

Have a great day !
