### ISSUE TITLE
[Feature] OTA Update Support like Stock ROM's

### ISSUE THREAD

**Issue by PauloArthur531** [ananjaser1211/FloydQ_Reports#222]
Floyd Q ROM update suggestion to update through settings. Like original Samsung softwares. For example: "Settings> Software Updates> "Update to Floyd Q ROM V6.0""

**Comment by SypeR54** [comment]
Hello @PauloArthur531 ,

Patching stock Samsung Software Update system is so much complicated and probably dont worth for the work. Because we need the code from stratch and host a OTA server, OTA XML and also patch our AROMA script to make it compatible with OTA.

However, maybe we can use different idea for checking only "changelist" updates. Atleast with that, non-Telegram users too can follow the latest releases via (i.e) notifications.

Thanks for the request. We'll discuss about that idea. :)

**Comment by ananjaser1211** [comment]
Implementing OTA support is not feasible or me, i dont have the infrastructure to hold a server to host hundreds of downloads per day (this rom gets over 3K downloads on first day of release, and ~100 new downloads every day as tracked by bit.ly)

i am not into hosting a paid server either, updates will done manually
