### ISSUE TITLE
[ISSUE] Data Speed in WIFI and Cellular

### ISSUE THREAD

**Issue by acharjyanisankh** [ananjaser1211/FloydQ_Reports#229]
if i do use the stock Samsung ROM in S7 edge model than the internet speed through cellular and WIFI is higher than the recent Floyd ROM 

 - Device: Galaxy S7 Edge
 - Model:  G935F

Cellular network : LTE based 
wifi infrastructure : Enterprise setup ( 1GBPS )

**Comment by SypeR54** [comment]
How much difference you have? Also speed is depends on your location, angle and router/cell tower load etc. However in my usage case, both of stock and Floyd gets similar results in WiFi and LTE setup.

Also if there is a "big" difference in both stock and Floyd rom, @ananjaser1211 can immediately feel the difference. Because he has 1Gbps network in his home with a couple of devices (such as S9+, S6, Note 4, iPhone X etc. etc.)

**Comment by ananjaser1211** [comment]
the only time i get lower speeds is if i am using 2.4 connection and bluetooth. other than that speed matches my other devices on my home connection (250mbps) and work connection (500mbps)

i cant test much in LTE as i dont use it.

**Comment by ananjaser1211** [comment]
Closing as no one else is reporting anything similar / no further discussion
