### ISSUE TITLE
[BUG] Delay when Startup

### ISSUE THREAD

**Issue by bugger23** [ananjaser1211/FloydQ_Reports#246]
When i try to reboot my phone, it has a kind of 3 Seconds delay when its starting up and showing the Samsung Galaxy S7 Boot logo. Also when the startup is finished, the device has huge lags when typing the PIN of my SIM-Card.

**To Reproduce**
1. Just Reboot the device and then you will see.
2. Type the PIN of your SIM-Card

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

Samsung Galaxy S7 (SM-G930F)

**Comment by reaitten** [comment]
I believe that the delay when startup is normal, since the phone needs to cache everything for normal use.
Again, do not quote on me on this, but this is normal since it happeneds to me everytime I restart my phone, but once the phone is on the lock screen, I would wait a little bit (like a minute max) then the lag would go away, and the phone would be normal.

Anyone can correct me if I am mistaken.

**Comment by ananjaser1211** [comment]
considering this happens on my S9+, i dont see how its abnormal, phone is booting, needs time to fully startup

**Comment by bugger23** [comment]
So theres no way how to fix it? If not ,then its not so bad. I can live with it.

**Comment by ananjaser1211** [comment]
i dont see how this can be fixed, probably the oneui 2 startup sequence is just too heavy, if it lags on exynos9810 and 8895, no wonder it does on 8890 too

**Comment by bugger23** [comment]
Ok then, i'll close this session.
