### ISSUE TITLE
[BUG] Camera is not functionally works good

### ISSUE THREAD

**Issue by Meruembr** [ananjaser1211/FloydQ_Reports#273]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by SypeR54** [comment]
No, camera is working good on our every test. Make sure you have enough space in your device (atleast 10% percent internal storage). Otherwise everything is good.

Also since Android 7, Samsung's camera UI doesn't changed so drastically. It keeps the same minimalism and principles. And lastly, we can't up-port Samsung's old camera app due to Samsung's limitations. It creates so much headache and issues.

I'm closing this issue since it's not contain any valid Bug or Issue. Thanks for reaching us.
