### ISSUE TITLE
[BUG] Audio disortion when using Bluetooth headset

### ISSUE THREAD

**Issue by SyntaxBreak** [ananjaser1211/FloydQ_Reports#276]
**Describe the bug**
Call audio is all screechy when using Bluetooth (only calls, not audio)

**To Reproduce**
1. Connect phone to Bluetooth device that can be used for calls
2. Get or make a call
3. Hear the screeching

**Expected behavior**
Call to be fine

**Smartphone:**
 - Galaxy S7 Edge
 - G935F

**Comment by SypeR54** [comment]
Since we can't reproduce this issue on Bluetooth speakers (with ANC supported and w/o ANC supported), you should provide some Logcat logs.

Can you provide some logs? Thanks.

**Comment by Kiaan-Wijayasekara** [comment]
How do I report logs?Sent from Kiaan's Galaxy S7 Edge
-------- Original message --------From: Yasin SypeR ***@***.***> Date: 16/08/2021  18:36  (GMT+05:30) To: ananjaser1211/FloydQ_Reports ***@***.***> Cc: Kiaan-Wijayasekara ***@***.***>, Author ***@***.***> Subject: Re: [ananjaser1211/FloydQ_Reports] [BUG] Audio disortion when using
  Bluetooth headset (#276) 
Since we can't reproduce this issue on Bluetooth speakers (with ANC supported and w/o ANC supported), you should provide some Logcat logs.
Can you provide some logs? Thanks.

**Comment by Kiaan-Wijayasekara** [comment]
Sent from Kiaan's Galaxy S7 Edge
