### ISSUE TITLE
[BUG] Keylights are enabled all the time when watching a video in the Google Drive app

### ISSUE THREAD

**Issue by aykuxt** [ananjaser1211/FloydQ_Reports#58]
Keylights are enabled all the time when watching a video in the Google Drive app. Not sure if it's a new bug by Google Drive or the rom but this never happened before.

**Steps to reproduce the behavior:**
1. Go to Google Drive
2. Click on a random video
3. Keylights are enabled all the time until video is stopped

**Expected behavior**
Keylights should not been enabled at all

**Smartphone:**
 - Device: Galaxy S7
 - Model: G930F

**Comment by ananjaser1211** [comment]
This is probably due to the shitty keylight behaviour we have (which does not register to some events)

as a temporary solution you can download this app https://play.google.com/store/apps/details?id=com.kunkunsoft.buttonlight

and set the keylight to always off. so it does not keep poping up in players.

this bug will be fixed when the main keylight issue is resolved

**Comment by ananjaser1211** [comment]
Moved to #102
